### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by dev-nasrullah**
No children specified

### CODE REVIEW

**Review by jgithaiga — APPROVED** [review]

**Comment by akanz** [comment]
this should be merged

**Review by guy-shahine — APPROVED** [review]

**Review by rahultyagi-mb — APPROVED** [review]

**Review by GideonAgboba — APPROVED** [review]
@nysamnang @van1985  please MERGE!!!!!!!!!!

**Comment by van1985** [comment]
I don't have access to merge, but go for it!

**Comment by iMnoorfahad** [comment]
yes this is really needed. please 🙏 merge this.

**Comment by pSnehanshu** [comment]
If this change is blocking anyone, please apply this change using [patch-package](https://www.npmjs.com/package/patch-package). Or if you're using Yarn or pnpm, you can use [yarn patch](https://yarnpkg.com/cli/patch) or [pnpm patch](https://pnpm.io/cli/patch).

**Comment by nonam4** [comment]
is this project abandoned?

**Comment by nonam4** [comment]
I've created a [package](https://www.npmjs.com/package/@nonam4/react-native-bottom-sheet) with this update

**Review by iMnoorfahad — APPROVED** [review]
this should be merged

**Comment by mashwishi** [comment]
still not working 

ERROR:

```
No overload matches this call.
  Overload 1 of 2, '(props: RBSheetProps | Readonly<RBSheetProps>): RBSheet', gave the following error.
    Type '{ children: Element; ref: MutableRefObject<any>; closeOnDragDown: true; closeOnPressMask: false; customStyles: { wrapper: { backgroundColor: string; }; draggableIcon: { ...; }; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<RBSheet> & Readonly<RBSheetProps>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RBSheet> & Readonly<RBSheetProps>'.
  Overload 2 of 2, '(props: RBSheetProps, context: any): RBSheet', gave the following error.
    Type '{ children: Element; ref: MutableRefObject<any>; closeOnDragDown: true; closeOnPressMask: false; customStyles: { wrapper: { backgroundColor: string; }; draggableIcon: { ...; }; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<RBSheet> & Readonly<RBSheetProps>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RBSheet> & Readonly<RBSheetProps>'.ts(2769)
      ```

**Pull request merged**
