### PR TITLE
add mask accessibility

### PR DESCRIPTION
**Pull request by johhansantana**
I've added some accessibility functionality to the component, mostly to be able to let the user know how to close the drawer/modal/sheet.

### CODE REVIEW

**Comment by nysamnang** [comment]
Thank @johhansantana for taking the time to improve this lib. Anyway, I won't merge this code unless other developers need to extend this feature because my vision is just want to make this lib lightweight and very simple to use that's why I don't want to add more and more useless props.

**Comment by rgaba** [comment]
@johhansantana - Thank you so much! I'm new to React Native and this is EXACTLY what I was looking for! This is a HUGE improvement from an accessibility point of view!

**Comment by rgaba** [comment]
@nysamnang - I am another one of those developers that would REALLY like to see this pull request get approved.  Can you please consider adding it to master? I'm sure there are many other developers and users with disabilities that would find this extremely helpful.

**Comment by norbiu** [comment]
@nysamnang Accessibility isn’t a ‘useless prop’. it’s essential for making apps usable for everyone. Dismissing it like this is honestly disappointing. A lot of developers rely on this library in their apps where accessibility isn’t optional, so it’s frustrating to see the issue shut down instead of discussed.

**Pull request closed without merging**
