### PR TITLE
Add "onOpen" prop function: triggered when opening the bottom sheet

### PR DESCRIPTION
**Pull request by Pandazaur**
Hello,

I just added a new trigger function when opening the bottom sheet, useful to trigger an action once the modal is shown

### CODE REVIEW

**Comment by nysamnang** [comment]
@Pandazaur What is additionnalData? Why do we need to pass additionnalData to onOpen method?

**Comment by Pandazaur** [comment]
Sometimes, you need to initialize your modal with data. 
Example: I need to edit a member from a list in a modal, I can get the member object through the `onOpen()` function and initialize my modal with it rather than pass it by props.

```javascript
// Open the modal
this.myModalRef.open(myMemberObject)


// The modal
< RBSheet onOpen={member => doSomething(member)}>
    ....
</RBSheet>
```

**Comment by nysamnang** [comment]
@Pandazaur I got your point. However, I think we no need to add onOpen as a props.
This is what we can do instead:
```
// Open the modal
onOpenModal = (myMemberObject, ...) => {
  this.myModalRef.open();
  doSomething(myMemberObject);
}
```
Doesn't this simple code work?

**Comment by Pandazaur** [comment]
@nysamnang It's complicated if you have your <RBSheet/> in a different component of where you call the `open()`. 

I give you another example of my case

```
class Container extends React.Component {
    constructor(props) {
        super(props)

        this.modalRef = null
    }

    componentDidMount() {
        const member = {...}

        this.modalRef.open(member)
    }

    return (
        <View>
            // ... Some code ...

            <MyModal customRef={ref => this.modalRef = ref} />
        </View>
    )
} 

class MyModal extends React.Component {
    onOpenModal = (member) => {
        /*
            I can initialize data in a different component without having to pass it by props
            and without needing to have a `member` object in the state of the `Container` component

            If I passed `member` as props, it would be reactive to changes from the parent but if I need
            to pass it only once and not being reactive to changes from the parent ?
        */ 

        // Other example: I can now trigger a request when the modal is show up to get some details on my API
        API.getMyMemberDetails(member)

    }

    return (
        <RBSheet ref={this.props.customRef} onOpen={this.onOpenModal}>
            // Some code
        </RBSheet>
   )
} 

```

In my case I think a `onOpen` trigger would be very interesting

**Comment by nysamnang** [comment]
cool

**Pull request merged**
