### PR TITLE
Animated Native Driver Support for Android / IOS

### PR DESCRIPTION
**Pull request by gstcarv**
## The Native Driver

NativeDriver can be used to, instead of Javascript animations, give the native responsibility, so you can have higher performance 60fps animations.

see: https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated

However, the "height" property is not supported by Native Driver, so instead of using the height, I used the "transform" property for that

### other

A new function called "openBottomSheet" was also created, which executes when the modal appears. That is, BottomSheet will only go up when Modal animation is over, avoiding cuts in BottomSheet animation

### CODE REVIEW

**Comment by itsam** [comment]
Hello, thank you for your work. Do you have any plans to merge this on master?

**Comment by rsallar** [comment]
Can we merge this, please?

**Comment by radko93** [comment]
I tried to test this code and it does not seem that it works well at least for me.

**Comment by nysamnang** [comment]
#2

**Comment by acerbastimur** [comment]
Can we use this feature now ?

**Pull request closed without merging**
