### PR TITLE
support ScrollView while using closeOnDragDown

### PR DESCRIPTION
**Pull request by rhrahul**

### CODE REVIEW

**Comment by sekizlipenguen** [comment]
hi,
Doesn't work for label "FlatList" :(

**Comment by rhrahul** [comment]
@sekizlipenguen , check now

**Comment by KjellConnelly** [comment]
I know it's been a few weeks, but just wondering if you can merge this request if it's working? My UI looks good on portrait mode, but gets really janky on landscape, plus I don't want to try to fit my UI for different devices. Scrollview is really needed along with the drag to close option (makes it feel like a real mobile app instead of just a website)

**Comment by KjellConnelly** [comment]
I found a solution to this problem that *may* have some performance or unknown interactions, but that works for me at least (A dragToClose raw-bottom-sheet where the top of it is drag to close, but the bottom 90% of it is a ScrollView)

Wrap your components in a TouchableWithoutFeedback:

```javascript
<RBSheet ref={ref=>this.RBSheet = ref} closeOnDragDown {...otherProps}>
   <ScrollView>
       <TouchableWithoutFeedback>
           <View>
               {children}
           </View>
       </TouchableWithoutFeedback>
   </ScrollView>
</RBSheet>

// Note* TouchableWithoutFeedback can only have a single child, hence the View component.
```

**Comment by nysamnang** [comment]
Hello @rhrahul @KjellConnelly, as you can see everything is working fine in my example. I'm not able to use your snippet code to test, so could you please create a new simple snippet to prove it doesn't work?

**Comment by rhrahul** [comment]
Hi @nysamnang, ScrollView as a child with closeOnDragDown is not working in current code, you can check it, and let me know :)

**Comment by nysamnang** [comment]
Screen Shot 2563-03-19 at 9 20 08 PM

@rhrahul  This code is in the example folder and it works normally!

**Comment by rhrahul** [comment]
> Screen Shot 2563-03-19 at 9 20 08 PM
> 
> @rhrahul This code is in the example folder and it works normally!

Strange !!
It wasn't working for me that's why I've to made these changes in code.

**Comment by chramos** [comment]
only works when the all modal content is wrapped with any touchable component

**Pull request closed without merging**
