### PR TITLE
More Customization Modal

### PR DESCRIPTION
**Pull request by moh3n9595**
With `customModalProps` it is possible to more customize modal component, e.g., set statusBarTranslucent

### CODE REVIEW

**Review by mikem3d — APPROVED** [review]

**Comment by mikem3d** [comment]
Let's get this merged!

**Comment by dayaki** [comment]
Need this for a project am currently working on....please merge

**Comment by MobileRP** [comment]
Will this PR be merged in near future?  Please merge

**Comment by moh3n9595** [comment]
Unfortunately, after a year seems the project is dead. No maintenance anymore.

**Comment by allindeveloper** [comment]
Please can this PR be merged ?

**Comment by KashyapKarkar** [comment]
How will we be able to use this PR ?

**Comment by surbhitrao** [comment]
To use this simply make this change in your package.json

-`"react-native-raw-bottom-sheet": "^2.2.0",` 
+`"react-native-raw-bottom-sheet": "git+https://github.com/moh3n9595/react-native-raw-bottom-sheet.git"
`


And pass this prop in RBSheet component
`<RBSheet
    customModalProps={{ statusBarTranslucent: true }}`

**Pull request merged**
